version: 2

multi-ecosystem-groups:
  zrooms:
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 3

updates:
  - package-ecosystem: "gomod"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "zrooms"

  - package-ecosystem: "github-actions"
    directory: "/"
    patterns: ["*"]
    multi-ecosystem-group: "zrooms"
