apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  labels:
    team: appsec
  name: zrooms
  namespace: appsec
  annotations:
    texas.nais.io/enabled: "true"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
spec:
  image: "{{ image }}"
  port: 8080
  ingresses:
    - https://zrooms.nav.no
  accessPolicy:
    outbound:
      external:
        - host: zoom.us
  azure:
    application:
      enabled: true
      allowAllUsers: true
      claims:
        extra:
          - "NAVident"
    sidecar:
      enabled: true
      autoLogin: true
      autoLoginIgnorePaths:
        - /oauth
        - /webhook
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 90
  resources:
    limits:
      memory: "32Mi"
    requests:
      cpu: "10m"
      memory: "16Mi"
  liveness:
    initialDelay: 10
    path: health/live
  readiness:
    initialDelay: 10
    path: health/ready
  envFrom:
    - secret: zrooms
  env:
    - name: REDIS_ENABLED
      value: "false"
    - name: "NAV_IDENT_ADMINS"
      value: "A158227"
  observability:
    logging:
      destinations:
        - id: loki
